Repository AY2425S1-CS2103T-F15-1/tp, pull requests merged in 2024-11, with the labels that each got.

#138 Update HelpWindow.java for new commands
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Enhancement, type.Task, priority.High

#135 Refactor priority command format and testcases
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/main/java/seedu/address/logic/parser/PriorityCommandParser.java
  src/test/java/seedu/address/logic/commands/PriorityCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/PriorityCommandParserTest.java
Labels: alpha-bug

#142 Update UI
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListPanel.css
  src/main/resources/view/TaskListPanel.fxml
Labels: type.Enhancement, type.Task, priority.High

#134 Change implementation of EmergencyContact to take in Name and Phone fields instead of Strings
  src/main/java/seedu/address/logic/commands/DeleteEmergencyContactCommand.java
  src/main/java/seedu/address/logic/commands/EmergencyContactCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EmergencyContactCommandParser.java
  src/main/java/seedu/address/model/person/EmergencyContact.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalTasksAddressBook.json
  src/test/java/seedu/address/logic/commands/DeleteEmergencyContactCommandTest.java
  src/test/java/seedu/address/logic/commands/EmergencyContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EmergencyContactCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#147 Fix UI for displaying list of tasks
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, priority.High, severity.High, alpha-bug

#143 Add How to Install NovaCare and Command Summary section of NovaCare
  docs/UserGuide.md
  docs/images/GUIOverview.jpg
  docs/images/assets.png
  docs/images/mac-java.png
  docs/images/windows-java.png
Labels: priority.Medium

#155 Fix tasks not saving their completion status
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalTasksAddressBook.json
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#152 Fix incorrect task status colour bug
  src/main/java/seedu/address/ui/TaskListPanel.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#157 Update UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium, severity.VeryLow

#150 Fix UserGuide title and emojis
  docs/UserGuide.md
Labels: priority.Medium, severity.VeryLow, alpha-bug

#161 Fix UG title heading and formatting
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.Low, alpha-bug

#146 Edit command bugfix
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/test/java/seedu/address/logic/commands/PriorityCommandTest.java
Labels: severity.High, alpha-bug

#149 Update DeveloperGuide
  docs/DeveloperGuide.md
  docs/images/Ui.png
  docs/index.md
Labels: priority.High, alpha-bug

#164 Fix add patient contact information to check that no name and phone number exists in record
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: severity.Medium, alpha-bug

#163 Fix UG Overview image with labeling and annotation section
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/GUIOverview.PNG
  docs/images/GUIOverview.jpg
Labels: severity.Low, alpha-bug

#167 Update UG
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.High, alpha-bug

#169 Rearrange help command list
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#172 Edit UG :x: emoji
  docs/UserGuide.md
Labels: type.Bug, priority.Low, severity.Low, alpha-bug

#178 Update use cases and model diagram
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
Labels: type.Enhancement, priority.Low, severity.Low

#181 Bug fix for list incomplete
  src/main/java/seedu/address/logic/commands/ListIncompleteCommand.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#180 Refactor and fix bugs for add task and priority command
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/PriorityCommandParser.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PriorityCommandParserTest.java
Labels: alpha-bug

#184 Update UG features grammer and syntax
  docs/UserGuide.md
Labels: type.Enhancement, priority.Low, severity.VeryLow

#186 Change delemergency command word to deleteemergency
  src/main/java/seedu/address/logic/commands/DeleteEmergencyContactCommand.java
Labels: type.Enhancement, priority.Low, severity.VeryLow

#189 Create command to unmark tasks
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UnmarkTaskCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkTaskCommandParserTest.java
Labels: type.Enhancement, priority.High, severity.High

#191 Update UG for unmarktask
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.High, alpha-bug

#193 Adjust storage logic
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidTaskAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#196 Add logic and test for thrown exception for null isComplete field
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#199 Fix hyperlinks in UG table of contents
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.High

#274 Update UG
  docs/UserGuide.md
  docs/images/AddTaskExample1.png
  docs/images/AddTaskExample2.png
  docs/images/FindPatientExample.png
  docs/images/findAlexDavidResult.png
Labels: type.Bug, priority.Medium, severity.Medium

#278 Fix help window to be scrollable
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, priority.High, severity.High, alpha-bug

#276 Fix terminology and ensure consistency of terms used
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEmergencyContactCommand.java
  src/main/java/seedu/address/logic/commands/DeletePriorityCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListIncompleteCommand.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListIncompleteCommandTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#283 Fix PersonCard to be horizontal scrollable
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#282 Add tip in UG features section to emphasize on compulsory fields
  docs/UserGuide.md
Labels: type.Bug, priority.Low, severity.Low

#280 Fix bugs in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.Medium

#275 Replace all instance of address book to NovaCare found in logging and UI
  docs/images/helpWindow.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/EmergencyContact.java
  src/main/java/seedu/address/model/person/PriorityLevel.java
  src/main/java/seedu/address/model/task/Task.java
Labels: type.Bug, severity.Low

#285 Fix TaskCard to be scrollable
  src/main/resources/view/TaskListCard.fxml
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#286 Add Planned Enhancements appendix to DG
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, priority.High

#287 Update User Guide and changed person to patient
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EmergencyContactCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
Labels: type.Bug, priority.Medium

#289 Update use cases in DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.High

#291 Update instructions for manual testing in DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.High

#293 Fix storage logic to skip tasks related to corrupted patients
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#295 Add tip in emergency contact feature section regarding duplicates
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.Low

#299 Update UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.High

#300 Add planned enhancements regarding priority feature
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Low

#303 Grammar issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: severity.Low

#306 Update UG formatting and improve standardisation
  docs/UserGuide.md
Labels: type.Enhancement, priority.Low, severity.Low

#308 Update syntax of UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.High

#309 Fixing a local part constraint and removing 1 reduandent header in table of content
  docs/UserGuide.md
Labels: type.Enhancement, priority.High

#315 Update Developer guide
  docs/DeveloperGuide.md
Labels: priority.High

#316 Add blank space to use cases section of DG
  docs/DeveloperGuide.md
Labels: priority.High, severity.VeryLow

#318 Fix capitalisation in UG
  docs/UserGuide.md
Labels: priority.High, severity.VeryLow
