Repository AY2425S1-CS2103T-F15-1/tp, pull requests merged in 2024-10, with the labels that each got.

#25 Add gavinsoh's Photo to team repo
  docs/images/gavinsoh.png
Labels: type.Task

#23 Add Benjamin's photo to team repo
  docs/images/benjibase.png
Labels: type.Task

#36 Add photo to team repo
  docs/images/yixianggg.png
Labels: type.Task

#42 Add jarrell photo
  README.md
  docs/images/jarrellc1.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task

#38 Update AboutUs for yixianggg
  docs/AboutUs.md
Labels: type.Task

#41 Update about us jarrellc1
  docs/AboutUs.md
Labels: type.Task

#45 Update ReadMe for NovaCare
  README.md
  docs/images/Ui.png
Labels: type.Task

#49 Update ReadMe to remove traces of AB3
  README.md
Labels: type.Task

#50 Update DG to remove traces of AB3
  docs/DeveloperGuide.md
Labels: type.Task

#53 Create TaskList class
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
Labels: type.Enhancement, priority.High

#55 Add emergency contact class and tests, update parser
  src/main/java/seedu/address/logic/commands/EmergencyContactCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EmergencyContactCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EmergencyContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EmergencyContactCommandParserTest.java
Labels: type.Task, priority.High

#58 Add and integrate remark class, update tests
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EmergencyContactCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EmergencyContactCommandParser.java
  src/main/java/seedu/address/model/person/EmergencyContact.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/EmergencyContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EmergencyContactCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Enhancement, type.Task, priority.High

#65 Update storage and Ui to incorporate emergency contact
  src/main/java/seedu/address/logic/commands/EmergencyContactCommand.java
  src/main/java/seedu/address/model/person/EmergencyContact.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalTasksAddressBook.json
  src/test/java/seedu/address/logic/commands/EmergencyContactCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Task, priority.High

#67 Add PriorityCommandParserTest.java
  src/main/java/seedu/address/logic/parser/PriorityCommandParser.java
  src/test/java/seedu/address/logic/parser/PriorityCommandParserTest.java
Labels: type.Enhancement, severity.Low

#69 Update constants in PriorityCommand
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
Labels: priority.Low

#70 Edit Javadoc in EmergencyContactCommandParser class
  src/main/java/seedu/address/logic/parser/EmergencyContactCommandParser.java
Labels: type.Task, priority.Medium, severity.Low

#72 Update emergency contact command function to disallow overriding persons that already have existing emergency contacts
  src/main/java/seedu/address/logic/commands/EmergencyContactCommand.java
  src/test/java/seedu/address/logic/commands/EmergencyContactCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Task, priority.High

#73 Update userGuide to align with current specification
  docs/UserGuide.md
  docs/images/PersonListExample.png
  docs/images/TaskListExample.png
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
Labels: type.Story, priority.Medium

#75 Update UserGuide to include new commands
  docs/UserGuide.md
Labels: priority.Medium

#82 Add DeletePriorityCommand
  src/main/java/seedu/address/logic/commands/DeletePriorityCommand.java
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePriorityCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PriorityCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePriorityCommandTest.java
  src/test/java/seedu/address/logic/commands/PriorityCommandTest.java
  src/test/java/seedu/address/logic/parser/DeletePriorityCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/PriorityCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement, priority.Medium

#84 Add delete functionality for emergency contact
  src/main/java/seedu/address/logic/commands/DeleteEmergencyContactCommand.java
  src/main/java/seedu/address/logic/commands/EmergencyContactCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteEmergencyContactCommandParser.java
  src/main/java/seedu/address/ui/TaskListCard.java
  src/test/java/seedu/address/logic/commands/DeleteEmergencyContactCommandTest.java
  src/test/java/seedu/address/logic/commands/EmergencyContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteEmergencyContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
Labels: type.Enhancement, type.Task, priority.High

#89 Fix bug in emergency contact command which returns success message for emergency contacts with unfilled parameters
  src/main/java/seedu/address/logic/commands/EmergencyContactCommand.java
  src/test/java/seedu/address/logic/commands/EmergencyContactCommandTest.java
Labels: type.Bug, priority.High, severity.Low

#91 Add find task logic and test
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Enhancement, type.Task, priority.Medium

#96 Add ListIncompleteCommand
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListIncompleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ListIncompleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: type.Enhancement, type.Task, priority.Medium

#98 Add list task command
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ListTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Enhancement, type.Task, priority.Medium

#100 Enable assertions for Gradle
  build.gradle
Labels: priority.Low, severity.Low

#103 Update ModelClassDiagram for DG
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Enhancement, priority.Medium

#112 Update ModelClassDiagram to reflect Task
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.High

#115 Bug fix for delete
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: priority.High, severity.High

#113 Update ug
  docs/diagrams/UiClassDiagram.puml
Labels: type.Enhancement, type.Task, priority.High

#117 Fix a bug where priority is not reflected on task assigned to user
  src/main/java/seedu/address/logic/commands/DeletePriorityCommand.java
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Bug

#130 Fix emergency contact command messages to show person name only
  src/main/java/seedu/address/logic/commands/DeleteEmergencyContactCommand.java
  src/main/java/seedu/address/logic/commands/EmergencyContactCommand.java
  src/test/java/seedu/address/logic/commands/DeleteEmergencyContactCommandTest.java
  src/test/java/seedu/address/logic/commands/EmergencyContactCommandTest.java
Labels: type.Bug, priority.Medium, severity.Low, alpha-bug

#136 Add delemergency instructions to UG
  docs/UserGuide.md
Labels: type.Enhancement, type.Task, priority.High

#133 Refactor code and fix bugs
  src/main/java/seedu/address/logic/commands/DeleteEmergencyContactCommand.java
  src/main/java/seedu/address/logic/commands/EmergencyContactCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
Labels: alpha-bug
